- common_benchmark_suite/openxla/benchmark/def_types.py
Some changes to better structure the artifact information. The actual usage is demonstrated in #9 
- Create `ModelTestDataArtifact` to represent a single test data format
- Create `ModelArtifact` to better host derived model artifact information
> Refactor artifact representations of `Model` and `ModelTestData`

- .github/workflows/run_comparative_benchmark.yml
Add setup job to print informative git log and correctly decide runner group.
> Add setup job to comparative benchmark workflow

- common_benchmark_suite/openxla/benchmark/models/jax/t5_large/model.py
- comparative_benchmark/jax_xla/benchmark_all.sh
- comparative_benchmark/jax_xla/setup_venv.sh
Installs cpu-specific and cuda-specific JAX packages depending on which device is being benchmarked. Also some minor fixes to the JAX T5 implementation.
> Use platform-specific JAX packages

- devtools/db_import/db_import/in_memory_storage.py
- devtools/db_import/db_import/in_memory_storage_test.py
- devtools/db_import/db_import/local_storage.py
- devtools/db_import/db_import/rules_test.py
- devtools/db_import/db_import/storage.py
The tests for the `rules` was using an in-memory implementation of the cloud storage client API. I'm moving this into a separate file to be able to use that from other tests as well.
The implementation is now also complete in the sense that it is implementing the previously established storage protocols.
It is also adding the `prefix` parameter to the list_blobs function in the protocol and in both implementations (`LocalStorage` and `InMemoryStorage`).
> Move InMemoryStorage into separate file

- .github/workflows/run_comparative_benchmark.yml
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/model_definitions.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/test_data_definitions.py
- comparative_benchmark/jax_xla/benchmark_all.sh
- comparative_benchmark/jax_xla/run_benchmarks.py
- comparative_benchmark/utils.py
Instead of generating input tensors from raw data every time, download the preprocessed input data from GCS.
This change also rearranges the GCS model artifact directory. Now it follows:
```
gs://.../${MODEL_NAME}_${BATCH_SIZE}/input_npy.tgz
gs://.../${MODEL_NAME}_${BATCH_SIZE}/output_npy.tgz
gs://.../${MODEL_NAME}_${BATCH_SIZE}/stablehlo.mlir
```
`input_npy.tgz` will pack multiple `.npy` if there are more than one input tensors.
> Fetch preprocessed inputs for benchmarking 

- devtools/db_import/cli.py
- devtools/db_import/db_import/batch_import.py
- devtools/db_import/db_import/batch_import_test.py
- devtools/db_import/db_import/db.py
- devtools/db_import/db_import/in_memory_database.py
- devtools/db_import/db_import/in_memory_storage.py
This is adding a new tool to the CLI, the batch import.
The batch import can scan through all the files in an existing GCS bucket and trigger the import pipeline as if all those files were just uploaded. It's usually needed when a new pipeline is set up and when we want to import all the existing data.
> Add batch import tool to DB import

- devtools/db_import/cli.py
- devtools/db_import/db_import/batch_import.py
- devtools/db_import/db_import/download.py
- devtools/db_import/db_import/process.py
- devtools/db_import/db_import/rules.py
- devtools/db_import/db_import/rules_test.py
This is adding a small helper tool to the CLI which allows the user to download all the needed files from a bucket to their local hard drive.
The tool accepts the name of a pipeline configuration as an argument, then gets a list of all the files from the bucket associated with the config. Each file is treated as a trigger to the pipeline, similar to how the batch import works.
The user will end up with a local copy of all the files that are needed to trigger the cloud function locally.
In the example of IREE:
- Benchmark traces would NOT be downloaded because the config leaves those alone
- benchmark-results-*.json files will be downloaded because these are valid triggers of the pipeline
- execution-benchmark-config.json files will ALSO be downloaded because the data transformation step …
> Add download helper tool

- devtools/db_import/cli.py
- devtools/db_import/db_import/deploy.py
This adds a deploy command to the CLI tool.
The deploy command can deploy a cloud function.
It reads the config from config file and takes care of all the steps:
1. Creating the cloud function.
2. Creating the trigger.
3. Authorizing the cloud function's service account to write to the destination bigquery table.
4. Authorizing the trigger to call the cloud function.
5. Authorizing the bucket's service account to trigger the trigger.
6. (Optional) Create the table
7. (Optional) Delete old data already in a table.
8. (Optional) Perform a batch import of files already existing in the source bucket.
It does all these steps the simple way by calling `glcoud` and `bq`. I think it would be possible to do all of that using only REST APIs but that would be a lot harder to implement.
That also …
> Add deployment tool to DB Import

- devtools/db_import/db_import/batch_import.py
- devtools/db_import/db_import/config.py
- devtools/db_import/db_import/deploy.py
- devtools/db_import/db_import/download.py
- devtools/db_import/db_import/process.py
- devtools/db_import/main.py
This renames the main config key in the config file from `cloud_functions` to `pipelines` because this will make the usage of terms in the documentation more consistent.
It's because each entry under `pipelines` has the configuration of the full assembly, not just the cloud function. The cloud function is just one aspect of it, that why the docs call it a pipeline.
> [DB Import] Rename cloud_functions config key to pipelines

- devtools/db_import/.gcloudignore
- devtools/db_import/cli.py
- devtools/db_import/db_import/config.py
- devtools/db_import/db_import/config_test.py
- devtools/db_import/main.py
This is doing 2 things:
1. Instead of calling `yaml.safe_load` in all places where we load the config file, this is now done in a single place behind a function.
2. In addition this introduces the `!embed` YAML tag. It allows loading the contents from a given filepath into an arbitrary YAML node. It's made for simplifying the config file by offloading big chunks of JSONnet code into a separate file.
> [DB Import] Factor out config loading and add embedding support

- devtools/db_import/db_import/deploy.py
The deploy command can automatically create the destination table in bigquery if it didn't exist beforehand. So far it was using the bq command line tool for that.
This change replaces the bq call by a SQL command because we will need the SQL command anyway for automatically creating tables with the bigquery emulator.
> [DB Import] Replace bq mk by SQL in deploy command

- devtools/db_import/cli.py
- devtools/db_import/db_import/verify.py
The `verify` command allows testing the whole pipeline locally without the need for a BigQuery database server or temporary table, or without the need for deploying a cloud function.
It uses the bigquery-emulator to spin up a local in memory database that behaves like BigQuery. It then trigger the cloud function processing code for a set of predefined files that already exist in the source bucket. Afterwards it executes a series of predefined SQL queries to check whether all the data has been correctly imported into the database.
> [DB Import] Add verify subcommand to CLI tool

- comparative_benchmark/jax_xla/run_benchmarks.py
Benchmark test: https://github.com/openxla/openxla-benchmark/actions/runs/5571392981
> Change JAX compile time from seconds to milliseconds

- .github/workflows/db_import.yml
- devtools/db_import/Dockerfile.presubmit
- devtools/db_import/cli.py
- devtools/db_import/config.yml
- devtools/db_import/db_import/config.py
- devtools/db_import/requirements.txt
- devtools/docker/dockerfiles/db_import.Dockerfile
- devtools/docker/image_deps.json
- devtools/docker/prod_digests.txt
This PR is adding a few related things at the same time (Apologies for that.):
1. It introduces a new CLI command `config` which adds to utility functions for handling config files: `cli.py config dump` dumps the entire config after YAML processing and `cli.py config list_pipelines` returns a newline-separated list with all the defined pipelines.
2. It is adding a Docker image definition for running presubmit checks in a Docker container. The purpose of the Docker container is mainly to build the bigquery-emulator. (It's a golang-tool and needs to be built from source)
3. It is adding a GitHub Actions workflow that first builds the Docker image and then runs the unit and integration tests.
4. It is adding a dummy pipeline config which is needed to see whether the integration tests work.
> [DB Import] Add presubmit check

- .github/workflows/run_comparative_benchmark.yml
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/model_definitions.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/pt/model_definitions.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/benchmark_definitions.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/model_definitions.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/test_data_definitions.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/utils.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/utils_test.py
- common_benchmark_suite/openxla/benchmark/def_types.py
- comparative_benchmark/xla_hlo/run_benchmarks.py
Instead of giving multiple URLs of the files under the model GCS directory, we can provide a single root GCS URL and all files can be downloaded under it.
This is also the first step to simplify test data definitions (#85). With this change, the generated test data can also be downloaded from the same root URL.
> Introduce URL of model artifacts dir

- .github/workflows/run_comparative_benchmark.yml
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/pt/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/devices/__init__.py
- common_benchmark_suite/openxla/benchmark/devices/host_devices.py
- common_benchmark_suite/openxla/benchmark/models/utils.py
- comparative_benchmark/benchmark_lib.py
- comparative_benchmark/jax_xla/run_benchmarks.py
- comparative_benchmark/pt_inductor/run_benchmarks.py
- comparative_benchmark/tf_xla/run_benchmarks.py
Add `--generate-artifacts` options to framework benchmark tools so users can run them without needing to download artifacts.
This is done by first generating the input artifacts then run the benchmarks. This option is useful when adding new benchmarks because their artifacts don't present in GCS yet.
Also add `host-cpu` and `host-gpu` devices for local run.
Here is an example to use this option to run benchmarks locally
```sh
./comparative_benchmark/pt_inductor/run_benchmarks.py \
-name "models/RESNET50_FP32_PT_.+" \
-device host-cpu \
-o /tmp/results.json \
--generate-artifacts \
--verbose
```
Tested on CPU benchmarks: https://github.com/openxla/openxla-benchmark/actions/runs/5651537135
Fix #86
> Make framework benchmarks locally runnable without downloading artifacts

- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/generate_model_artifacts.sh
- common_benchmark_suite/openxla/benchmark/comparative_suite/pt/scripts/generate_model_artifacts.sh
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/scripts/generate_model_artifacts.sh
Expose the filter option in `generate_model_artifacts.sh`, so users can generate artifacts selectively just in case.
Also print the path of output directory in the end and change the default `python` to `python3` (which seems to be more commonly presented on OS?).
The `iree-opt` is also passed by environment variable `IREE_OPT` instead and try to find it in system paths by default. I feel like this makes it easier to use by not passing `iree-opt` path every time.
Tested with the command on all three scripts:
```sh
common_benchmark_suite/openxla/benchmark/comparative_suite/pt/scripts/generate_model_artifacts.sh "BERT_LARGE_FP32_.+"
```
> Expose the filter option in `generate_model_artifacts.sh`

- .github/workflows/run_comparative_benchmark.yml
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/pt/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/models/jax/bert/bert_model.py
- common_benchmark_suite/openxla/benchmark/models/jax/gpt2/gpt2lmhead_model.py
- common_benchmark_suite/openxla/benchmark/models/jax/resnet/resnet_model.py
- common_benchmark_suite/openxla/benchmark/models/jax/t5/t5_for_conditional_generation.py
- common_benchmark_suite/openxla/benchmark/models/jax/t5/t5_model.py
- common_benchmark_suite/openxla/benchmark/models/model_interfaces.py
- common_benchmark_suite/openxla/benchmark/models/model_interfaces_test.py
- common_benchmark_suite/openxla/benchmark/models/pt/bert/bert_model.py
- common_benchmark_suite/openxla/benchmark/models/pt/resnet/resnet_model.py
- common_benchmark_suite/openxla/benchmark/models/tf/bert/bert_model.py
- common_benchmark_suite/openxla/benchmark/models/tf/efficientnet/efficientnet_model.py
- common_benchmark_suite/openxla/benchmark/models/tf/resnet/resnet_model.py
- common_benchmark_suite/openxla/benchmark/models/tf/t5/t5_model.py
- common_benchmark_suite/openxla/benchmark/models/utils.py
- common_benchmark_suite/openxla/benchmark/models/utils_test.py
- comparative_benchmark/jax_xla/run_benchmarks.py
- comparative_benchmark/pt_inductor/run_benchmarks.py
- comparative_benchmark/tf_xla/run_benchmarks.py
Since many ML frameworks (PyTorch and TF) don't accept tuple as parameters in forward function. Refactor the model interface to use parameters for multi-value inputs.
As the comment in the code, when `preprocess` returns a tuple, it will be treated as the argument list for the forward function, instead of passing the tuple directly.
Also improve the handling on the return value of `preprocess`. Now it can return a single value instead of packing it into a single element tuple. This is done by handling the non-tuple return value in generation scripts.
> Refactor model forward method to take parameters instead of tuple

- devtools/db_import/config.yml
This is adding a pipeline config for the comparative benchmarking results.
Most of the complexity in the commit comes from the SQL epxressions that are part of the config for unit testing. They are the same which we also use in the database and they need to support a variety of old data schemas that we have in the database.
> Add DB import config for comparative benchmarks

- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/generate_model_artifacts.sh
- common_benchmark_suite/openxla/benchmark/comparative_suite/pt/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/pt/scripts/generate_model_artifacts.sh
- common_benchmark_suite/openxla/benchmark/comparative_suite/pt/scripts/setup_venv.sh
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/scripts/generate_model_artifacts.sh
- common_benchmark_suite/openxla/benchmark/models/utils.py
Artifacts require a lot of disk space. This adds the option to upload artifacts to gcs as each model completes and deletes them locally once uploaded.
> Upload artifacts to gcs automatically

- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/scripts/generate_model_artifacts.sh
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/scripts/setup_venv.sh
It is possible to run into TF dependency version misalignment when generating TF artifacts i.e. the local venv version of TF may be out of sync with the version used in `iree-import-tf`. 
This PR removes use of `iree-import-tf` and imports the TF model into mlir directly using tf.mlir api's.
> Import TF to IREE directly instead of using iree-import-tf tool

- .github/workflows/run_ggml_benchmark.yml
- common_benchmark_suite/openxla/benchmark/comparative_suite/tf/model_definitions.py
- common_benchmark_suite/openxla/benchmark/def_types.py
- common_benchmark_suite/openxla/benchmark/devices/__init__.py
- common_benchmark_suite/openxla/benchmark/devices/mobile_devices.py
- devtools/docker/dockerfiles/android.Dockerfile
- devtools/docker/image_deps.json
- devtools/docker/prod_digests.txt
- experimental/ggml/benchmark_ggml.sh
- experimental/ggml/benchmark_lib.py
- experimental/ggml/build_ggml.sh
- experimental/ggml/requirements.txt
- experimental/ggml/run_benchmarks.py
- experimental/ggml/run_benchmarks_android.py
- experimental/ggml/set_android_scaling_governor.sh
- experimental/ggml/setup_venv.sh
Includes F32, F16 and INT4 versions.
> Add GPT-2 GGML x86 and Android Benchmarks

- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/generate_model_artifacts.sh
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/setup_venv.sh
Replace `iree-opt` with `iree-ir-tool`, which can be installed from the IREE release package
> Use iree-ir-tool from IREE release

- .github/workflows/run_comparative_benchmark.yml
We are no longer maintaining XLA server benchmarks.
> Disable comparative benchmarks

- devtools/db_import/db_import/deploy.py
The service account is a per-pipeline-property and needs to be handled for each pipeline individually instead of before.
> Fix cloud function deployment bug

- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/generate_model_artifacts.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/tflite/model_definitions.py
FP16 models require an additional experimental flag to use the latest XNNPack kernels.
> Regenerate TFLite FP16 models

- .github/workflows/run_comparative_benchmark.yml
- .github/workflows/run_mobile_comparative_benchmark.yml
- common_benchmark_suite/openxla/benchmark/comparative_suite/tflite/model_definitions.py
There have been some recent changes to StableHLO that requires regeneration of JAX and TFLite models. TF model generation is currently broken due to version skews across HuggingFace, TF, and Keras.
> Update JAX and TFLite Models

- experimental/iree/compile_workloads.py
Includes `--iree-llvmcpu-use-decompose-softmax-fuse=false` flag when compiling IREE vmfbs.
> Enable softmax

- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/scripts/setup_venv.sh
- common_benchmark_suite/openxla/benchmark/comparative_suite/tflite/scripts/setup_venv.sh
The `openxla.github.io` link depends on a specific GitHub organization, and the IREE repo will be moving soon (multiple times). The `iree.dev` release links URL is recommended here: https://iree.dev/reference/bindings/python/#prebuilt-packages
> Use stable URL for IREE pip-release-links.

- experimental/iree/compile_workloads.py
- experimental/tflite/build_tflite.sh
Replaces +v9a with +v9.2a CPU feature to fix IREE build failure:
```
error: 'llvm.call' op operand type mismatch for operand 0: '!llvm.struct<(ptr, ptr, i64)>' != '!llvm.ptr'
note: called from stablehlo.mlir:529:11:
note: see current operation: %120 = "llvm.call"(%34, %76, %7, %41, %84, %7, %48, %94, %7, %12, %12, %11, %10, %10, %9, %8, %96) <{CConv = #llvm.cconv<ccc>, callee = @iree_uk_mmt4d, fastmathFlags = #llvm.fastmath<none>}> : (!llvm.struct<(ptr, ptr, i64)>, i64, i64, !llvm.struct<(ptr, ptr, i64)>, i64, i64, !llvm.struct<(ptr, ptr, i64)>, i64, i64, i64, i64, i64, i32, i32, i32, i32, !llvm.ptr) -> i32
/tmp/jax_models_0.4.30_1719201699/T5_LARGE_FP32_JAX_512XI32_BATCH1/stablehlo.mlir:529:11: error: failed to run translation of source executable to target executable for backend …
```
> Fix build failures

- README.md
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/benchmark_definitions.py
- common_benchmark_suite/openxla/benchmark/comparative_suite/jax/model_definitions.py
- common_benchmark_suite/openxla/benchmark/models/jax/gemma/gemma_pipeline.py
- common_benchmark_suite/openxla/benchmark/models/jax/gemma/requirements.txt
These are floating point versions FP32, BF16 and FP32. Input sequence length is fixed at 1024 tokens and generates 256 tokens. The decode loop is included with greedy sampling and a kv cache.
> Add Gemma 2B IT models
